[workspace]
default-members = ["crates/pevm"]
members = ["bins/fetch", "crates/pevm"]
resolver = "2"

[profile.release]
codegen-units = 1
panic = "abort"
lto = "fat"

# Copied from https://github.com/paradigmxyz/reth/blob/bd8c4eceb20c39c6e501d06cf906469329340bb9/Cargo.toml#L159
[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.rust_2018_idioms = { level = "deny", priority = -1 }
rust.unreachable_pub = "warn"
rust.unused_crate_dependencies = "warn"
rust.unused_must_use = "deny"
rustdoc.all = "warn"
# rust.unnameable-types = "warn"

[workspace.lints.clippy]
# These are some of clippy's nursery (i.e., experimental) lints that we like.
# By default, nursery lints are allowed. Some of the lints below have made good
# suggestions which we fixed. The others didn't have any findings, so we can
# assume they don't have that many false positives. Let's enable them to
# prevent future problems.
borrow_as_ptr = "warn"
branches_sharing_code = "warn"
clear_with_drain = "warn"
cloned_instead_of_copied = "warn"
collection_is_never_read = "warn"
derive_partial_eq_without_eq = "warn"
doc_markdown = "warn"
empty_line_after_doc_comments = "warn"
empty_line_after_outer_attr = "warn"
enum_glob_use = "warn"
equatable_if_let = "warn"
explicit_into_iter_loop = "warn"
explicit_iter_loop = "warn"
flat_map_option = "warn"
from_iter_instead_of_collect = "warn"
if_not_else = "warn"
if_then_some_else_none = "warn"
implicit_clone = "warn"
imprecise_flops = "warn"
iter_on_empty_collections = "warn"
iter_on_single_items = "warn"
iter_with_drain = "warn"
iter_without_into_iter = "warn"
large_stack_frames = "warn"
manual_assert = "warn"
manual_clamp = "warn"
manual_is_variant_and = "warn"
manual_string_new = "warn"
match_same_arms = "warn"
missing_const_for_fn = "warn"
mutex_integer = "warn"
naive_bytecount = "warn"
needless_bitwise_bool = "warn"
needless_continue = "warn"
needless_for_each = "warn"
needless_pass_by_ref_mut = "warn"
nonstandard_macro_braces = "warn"
option_as_ref_cloned = "warn"
or_fun_call = "warn"
path_buf_push_overwrite = "warn"
read_zero_byte_vec = "warn"
redundant_clone = "warn"
redundant_else = "warn"
single_char_pattern = "warn"
string_lit_as_bytes = "warn"
string_lit_chars_any = "warn"
suboptimal_flops = "warn"
suspicious_operation_groupings = "warn"
trailing_empty_array = "warn"
trait_duplication_in_bounds = "warn"
transmute_undefined_repr = "warn"
trivial_regex = "warn"
tuple_array_conversions = "warn"
type_repetition_in_bounds = "warn"
uninhabited_references = "warn"
unnecessary_self_imports = "warn"
unnecessary_struct_initialization = "warn"
unnested_or_patterns = "warn"
unused_peekable = "warn"
unused_rounding = "warn"
use_self = "warn"
useless_let_if_seq = "warn"
while_float = "warn"
zero_sized_map_values = "warn"

# These are nursery lints which have findings. Allow them for now. Some are not
# quite mature enough for use in our codebase and some we don't really want.
# Explicitly listing should make it easier to fix in the future.
as_ptr_cast_mut = "allow"
cognitive_complexity = "allow"
debug_assert_with_mut_call = "allow"
fallible_impl_from = "allow"
future_not_send = "allow"
needless_collect = "allow"
non_send_fields_in_send_ty = "allow"
redundant_pub_crate = "allow"
significant_drop_in_scrutinee = "allow"
significant_drop_tightening = "allow"
too_long_first_doc_paragraph = "allow"


[workspace.dependencies]
pevm = { path = "crates/pevm", features = ["rpc-storage"] }

alloy-chains = "0.1.40"
alloy-consensus = "0.5.2"
alloy-primitives = { version = "0.8.8", features = [
  "asm-keccak",
  "map-fxhash",
] }
alloy-provider = "0.5.2"
alloy-rlp = "0.3.8"
alloy-rpc-types = "0.5.2"
alloy-transport = "0.5.2"
alloy-transport-http = "0.5.2"
alloy-trie = "0.7.2"

# Let's do our best to port needed REVM changes upstream
revme = { git = "https://github.com/risechain/revm", rev = "7345c07ae7f65a976e9db4866872066aef0bdce4" }
revm = { git = "https://github.com/risechain/revm", rev = "7345c07ae7f65a976e9db4866872066aef0bdce4", features = [
  "serde",
] }

# OP dependencies
op-alloy-consensus = "0.5.0"
op-alloy-network = "0.5.0"
op-alloy-rpc-types = "0.5.0"

bincode = "1.3.3"
# We can roll our own but [revm] depends on this anyway.
bitflags = "2.6.0"
bitvec = "1.0.1"
clap = { version = "4.5.20", features = ["derive"] }
criterion = "0.5.1"
dashmap = "6.1.0"
flate2 = "1.0.34"
hashbrown = "0.15.0"
rand = "0.8.5"
rayon = "1.10.0"
reqwest = "0.12.8"
rpmalloc = { version = "0.2.2", features = ["thread_cache", "global_cache"] }
rustc-hash = "2.0.0"
serde = "1.0.210"
serde_json = "1.0.132"
smallvec = "1.13.2"
snmalloc-rs = "0.3.6"
thiserror = "1.0.64"
tikv-jemallocator = "0.6.0"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
walkdir = "2.5.0"

